VQVAE:
    #Codebook Configs
    levels: 1
    downs_t: [3,]       # 3 -> 1
    strides_t : [2,]        # 2 -> 3
    emb_width : 512
    l_bins : 512
    l_mu : 0.99
    commit : 0.02
    hvqvae_multipliers : [1,]
    width: 512
    depth: 3
    m_conv : 1.0
    dilation_growth_rate : 3
    sample_length: 30
    use_bottleneck: True
    joint_channel: 9
    # depth: 3
    # width: 128
    # m_conv: 1.0
    # dilation_growth_rate: 1
    # dilation_cycle: None
    vel: 1      # 1 -> 0
    acc: 1      # 1 -> 0
    vqvae_reverse_decoder_dilation: True

# BEAT
train_data_path: "../dataset/BEAT/speaker_10_state_0/lmdb/lmdb_train"     # speaker_1_state_0
val_data_path: "../dataset/BEAT/speaker_10_state_0/lmdb/lmdb_valid"

# 60 fps + rotation lmdb
data_mean: [0.96776, 0.03511, -0.00725, -0.03507, 0.96983, -0.00267, 0.00705, 0.00363, 0.99770, 0.99930, 0.01376, 0.00255, -0.01374, 0.99938, -0.00253, -0.00263, 0.00236, 0.99987, 0.99216, 0.01860, -0.00709, -0.01882, 0.98965, -0.02039, 0.00531, 0.02222, 0.99601, 0.99612, -0.00993, -0.00998, 0.00991, 0.99691, -0.00743, 0.00991, 0.00820, 0.99890, 0.97768, 0.03605, 0.00750, -0.03840, 0.98164, 0.01540, -0.00722, -0.01537, 0.98648, 0.97946, 0.01763, 0.03590, -0.01997, 0.97667, 0.02363, -0.03636, -0.02139, 0.97316, 0.99365, 0.00565, 0.00280, -0.00546, 0.99544, -0.00042, -0.00264, 0.00288, 0.99802, 0.96583, -0.00000, 0.03884, -0.01122, 0.93705, 0.25010, -0.03542, -0.24257, 0.94337, 0.42426, -0.00898, 0.03954, 0.00077, 0.78974, -0.20711, -0.03733, 0.36827, 0.39807, 0.77377, -0.03384, -0.00000, 0.02925, 0.01928, -0.84132, 0.03604, 0.63766, 0.00386, 0.92148, -0.00060, 0.02677, 0.00000, 0.96406, 0.08089, -0.02854, -0.07688, 0.91554, 0.97416, 0.00000, 0.01114, 0.00433, 0.96865, -0.19804, -0.01083, 0.19909, 0.95347, 0.40921, -0.00936, -0.05575, -0.00286, 0.82451, 0.12718, 0.04597, -0.30625, 0.40531, 0.79050, 0.02049, 0.00000, 0.01737, -0.00978, 0.82851, 0.00535, -0.66105, -0.02535, 0.91757, -0.00631, 0.02182, -0.00000, 0.95817, -0.09851, -0.01829, 0.09236, 0.91430]
data_std: [0.02841, 0.23917, 0.06431, 0.23880, 0.02782, 0.01986, 0.06575, 0.01430, 0.00336, 0.00108, 0.03157, 0.01468, 0.03155, 0.00106, 0.00621, 0.01473, 0.00612, 0.00018, 0.01512, 0.11668, 0.03705, 0.11614, 0.01536, 0.07804, 0.03890, 0.07677, 0.00516, 0.00416, 0.07577, 0.04228, 0.07578, 0.00407, 0.01605, 0.04228, 0.01571, 0.00136, 0.02789, 0.15938, 0.12886, 0.15728, 0.02378, 0.09677, 0.13076, 0.09421, 0.02422, 0.03618, 0.12665, 0.14733, 0.12803, 0.07007, 0.15448, 0.14572, 0.15622, 0.07448, 0.02085, 0.09297, 0.05959, 0.09228, 0.01465, 0.01851, 0.06068, 0.01429, 0.00739, 0.20466, 0.00001, 0.15420, 0.04271, 0.19514, 0.13914, 0.14860, 0.15817, 0.05350, 0.16375, 0.29095, 0.84077, 0.46422, 0.24234, 0.24331, 0.75914, 0.31183, 0.17603, 0.28407, 0.56519, 0.00013, 0.23171, 0.44004, 0.20889, 0.51453, 0.28072, 0.49853, 0.18833, 0.07924, 0.32926, 0.00007, 0.16923, 0.18816, 0.33851, 0.17250, 0.10350, 0.10469, 0.00000, 0.19984, 0.04231, 0.09819, 0.10514, 0.19528, 0.11157, 0.02373, 0.15367, 0.26760, 0.85681, 0.43448, 0.24673, 0.23313, 0.78615, 0.30631, 0.16722, 0.28200, 0.54330, 0.00016, 0.22882, 0.44907, 0.24319, 0.49285, 0.25625, 0.50377, 0.20667, 0.07828, 0.32970, 0.00034, 0.19347, 0.18646, 0.33914, 0.17255, 0.10199]

n_poses: 240     # 30 -> 40 -> 240
n_codes: 30
motion_resampling_framerate: 60     # 20 -> 60
subdivision_stride: 32      # 10 -> 30
batch_size: 256
loader_workers: 2
epochs: 500     # 500 -> 10
save_per_epochs: 25     # 20 -> 1
model_save_path: "./output/train_codebook"
name: "codebook"

lr: 0.00003     # 0.00003 ->
betas: [0.5, 0.999]
milestones: [100, 200]
gamma: 0.1

end2end:
    lr: 0.0002
    epochs: 100
    betas: [0.99, 0.999]
    model_save_path: "./output/train_end2end"
    save_per_epochs: 10
    name: "end2end"

PAE:
    epochs: 100
    save_per_epochs: 10
    n_poses: 240
    subdivision_stride: 1
    model_save_path: "./output/train_PAE"
    figs_save_path: "./output/train_PAE/figs"
    name: "PAE"

beat_data_to_lmdb:
    path: "../dataset/BEAT/speaker_10_state_0"
    lmdb_name: "lmdb"
    mode: "rotation"
